[features]
seeds = false
skip-lint = false

[programs.devnet]
sol_wrapping_contract = "DX6quq5ypkFrGviQuMTX6KMLiEGVjnWaEXiDsVpNRP3e"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "Devnet"
wallet = "/Users/Temitope/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
